# Generated by Django 3.0.5 on 2020-04-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_photo',
            new_name='profile_pic',
        ),
    ]
